# @package _group_

count: 1

r0:
  type: ray_depth
  ray_chunk: 32768
  batch_size: 32768
  use_inp_freq: inf

  use_depth_embedding: False
  use_color_embedding: True

  dataset:
    name: random_view
    num_views: all

  weight:
    type: exponential_decay
    start: 0.5
    decay: 0.5
    num_epochs: 500

  lookup_loss:
    type: mae
    weight: 0.0
    warmup_iters: 1000

    angle_std: 5.0
    dist_std: 0.05

  color_loss:
    type: mae
    weight: 0.5

    angle_std: 5.0
    dist_std: 0.05

  depth_loss:
    type: mae
    weight: 0.5

    angle_std: 5.0
    dist_std: 0.05

  use_occ: False

  occ_loss:
    type: mae
    weight: 0.0

  range:
    pos: 1.0
    dir: 1.0

  jitter:
    pos: 0.1
    dir: 0.1

  param:
    n_dims: 6
    fn: pluecker

  pe:
    n_freqs: 10
    warmup_iters: 0
    max_freq_iter: 50000
    exclude_identity: False

  net:
    depth: 8
    hidden_channels: 384
    skips: [4]
    activation: 'identity'

  optimizer:
    optimizer: adam
    lr: 0.0005
    clip: False
    clip_amount: 1.0
    momentum: 0.9
    weight_decay: 0
    lr_scheduler: steplr
    warmup_multipler: 1.0
    warmup_epochs: 0

    decay_step: 500
    decay_gamma: 0.5

r1:
  type: teacher
  batch_size: 32768

  dataset:
    name: "dense_{config.dataset.name}"
    collection: "{config.dataset.collection}_dense"
    split: "train"
    root_dir: "{config.experiment.data_dir}/{config.dataset.data_subdir}/{config.dataset.collection}_dense/"

    num_rows: 10
    num_cols: 10

    size: 1000

    train_row_skip: 1
    train_col_skip: 1
    train_skip: 2

  weight:
    type: exponential_decay
    start: 1.0
    decay: 1.0
    decay_step: 500

  loss:
    type: mse
